import Head from 'next/head'
import Feed from '../components/Feed'
import Sidebar from '../components/Sidebar'
import {getProviders, getSession, useSession} from 'next-auth/react'
import Login from '../components/Login'
import { useRecoilState } from 'recoil'
import { modalState } from '../atom/modalAtom'
import Modal from '../components/Modal'
import Widgets from '../components/Widgets'


export default function Home({providers, trendingResults, followResults}) {
  const { data: session } = useSession()
  const [isOpen, setIsOpen] = useRecoilState(modalState);
  if(!session) return <Login providers={providers} />
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   <main className="bg-black min-h-screen flex max-w-[1400px] mx-auto">
   <Sidebar/>
   <Feed/>
   <Widgets trendingResults={trendingResults}
          followResults={followResults} />
    {isOpen && <Modal/>}
   </main>
    </div>
  )
}


export async function getServerSideProps(context){
  const trendingResults = await fetch("https://jsonkeeper.com/b/NKEV").then(
    (res) => res.json()
  );
  const followResults = await fetch("https://jsonkeeper.com/b/WWMJ").then(
    (res) => res.json()
  );
  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
      providers: providers,
      session: session,
      trendingResults: trendingResults,
      followResults: followResults,
    }
  }
}